/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import brickbreaker.*;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Hakim
 */
public class BrickBreakerManager extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form BrickBreakerManager
     */
//    private final Thread myThread;
//    private GameFrame g;
    private boolean loggedIn;

    public BrickBreakerManager() {
//        myThread = new Thread(this);
//        myThread.setName("MainThread");
        initComponents();
        System.out.println(btnAccountManager.getWidth());
        this.getContentPane().setBackground(Color.black);
//        this.getContentPane().setLayout(new BoxLayout());
//        myThread.start();
        //panel[0].add("Options", panel[2]);
        //jPanel1.add("Help", panel[3]);
        jPanel1.add("GamePanel", gamePanel = new GamePanel());
        //panel[0].add("NamePanel", panel[4]);
        jPanel1.add("LevelCreator", levelCreator = new LevelCreatorWizard());
        jPanel1.add("Levels", pane = new javax.swing.JScrollPane());
        jPanel1.add("Score", scoreScreen = new ScoreManager());
        jPanel1.add("AccountManager", mainDesk = new AccountManager());
        gamePanel.run();
        scoreScreen.startThread();
        mainDesk.startThread();
        mainDesk.suspendThread();
        pane.setViewportView(level = new LEVELS());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnExit = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnOptions = new javax.swing.JButton();
        btnLevels = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        lblPlay1 = new javax.swing.JLabel();
        lblLevels1 = new javax.swing.JLabel();
        lblOptions1 = new javax.swing.JLabel();
        lblHelp1 = new javax.swing.JLabel();
        lblExit1 = new javax.swing.JLabel();
        lblLevels2 = new javax.swing.JLabel();
        lblPlay2 = new javax.swing.JLabel();
        lblOptions2 = new javax.swing.JLabel();
        lblHelp2 = new javax.swing.JLabel();
        lblExit2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnAccountManager = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BRICKBREAKER!");
        setSize(new java.awt.Dimension(1000, 556));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setForeground(Color.YELLOW);
        jComboBox1.setBackground(Color.BLACK);
        jComboBox1.setModel(new DefaultComboBoxModel(new String[]{"Guest Scores", "Account Scores", "All Scores"}));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 358, 181, -1));

        jTextArea1.setLineWrap(true);
        jTextArea1.setBackground(Color.BLACK);
        jTextArea1.setForeground(Color.YELLOW);
        jTextArea1.setOpaque(false);
        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("HIGH SCORES:");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 181, 349));

        btnExit.setBorder(BorderFactory.createEmptyBorder());
        btnExit.setContentAreaFilled(false);
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnExit.setForeground(Color.YELLOW);
        btnExit.setText("EXIT");
        btnExit.addMouseListener(this);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 421, 122, -1));

        btnHelp.setBorder(BorderFactory.createEmptyBorder());
        btnHelp.setContentAreaFilled(false);
        btnHelp.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnHelp.setForeground(Color.YELLOW);
        btnHelp.setText("HELP");
        btnHelp.addMouseListener(this);
        getContentPane().add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 383, 122, -1));

        btnOptions.setBorder(BorderFactory.createEmptyBorder());
        btnOptions.setContentAreaFilled(false);
        btnOptions.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnOptions.setForeground(Color.YELLOW);
        btnOptions.setText("OPTIONS");
        btnOptions.addMouseListener(this);
        getContentPane().add(btnOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 345, 122, -1));

        btnLevels.setBorder(BorderFactory.createEmptyBorder());
        btnLevels.setContentAreaFilled(false);
        btnLevels.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnLevels.setForeground(Color.YELLOW);
        btnLevels.setText("LEVELS");
        btnLevels.addMouseListener(this);
        btnLevels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLevelsActionPerformed(evt);
            }
        });
        getContentPane().add(btnLevels, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 307, 122, -1));

        btnPlay.setBorder(BorderFactory.createEmptyBorder());
        btnPlay.setContentAreaFilled(false);
        btnPlay.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnPlay.addMouseListener(this);
        btnPlay.setText("PLAY");
        btnPlay.setForeground(Color.YELLOW);
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 269, 122, -1));

        lblPlay1.setForeground(Color.YELLOW);
        lblPlay1.setVisible(false);
        lblPlay1.setText("<<");
        getContentPane().add(lblPlay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 273, -1, -1));

        lblLevels1.setForeground(Color.YELLOW);
        lblLevels1.setVisible(false);
        lblLevels1.setText("<<");
        getContentPane().add(lblLevels1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 311, -1, -1));

        lblOptions1.setForeground(Color.YELLOW);
        lblOptions1.setVisible(false);
        lblOptions1.setText("<<");
        getContentPane().add(lblOptions1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 349, -1, -1));

        lblHelp1.setForeground(Color.YELLOW);
        lblHelp1.setVisible(false);
        lblHelp1.setText("<<");
        getContentPane().add(lblHelp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 387, -1, -1));

        lblExit1.setForeground(Color.YELLOW);
        lblExit1.setVisible(false);
        lblExit1.setText("<<");
        getContentPane().add(lblExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 425, -1, -1));

        lblLevels2.setForeground(Color.YELLOW);
        lblLevels2.setVisible(false);
        lblLevels2.setText(">>");
        getContentPane().add(lblLevels2, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 311, -1, -1));

        lblPlay2.setForeground(Color.YELLOW);
        lblPlay2.setVisible(false);
        lblPlay2.setText(">>");
        getContentPane().add(lblPlay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 273, -1, -1));

        lblOptions2.setForeground(Color.YELLOW);
        lblOptions2.setVisible(false);
        lblOptions2.setText(">>");
        getContentPane().add(lblOptions2, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 349, -1, -1));

        lblHelp2.setForeground(Color.YELLOW);
        lblHelp2.setVisible(false);
        lblHelp2.setText(">>");
        getContentPane().add(lblHelp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 387, -1, -1));

        lblExit2.setForeground(Color.YELLOW);
        lblExit2.setVisible(false);
        lblExit2.setText(">>");
        getContentPane().add(lblExit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 425, -1, -1));

        jLabel12.setForeground(Color.YELLOW);
        jLabel12.setFont(new java.awt.Font("Sitka Heading", 1, 48)); // NOI18N
        jLabel12.setText("BRICK BREAKER");
        jLabel12.setToolTipText("");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 134, -1, 70));

        btnAccountManager.setBackground(Color.BLACK);
        btnAccountManager.setForeground(Color.YELLOW);
        btnAccountManager.setBorderPainted(false);
        btnAccountManager.setFocusPainted(false);
        btnAccountManager.setContentAreaFilled(false);
        btnAccountManager.addMouseListener(this);
        btnAccountManager.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnAccountManager.setText("LogIn/Sign In");
        btnAccountManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountManagerActionPerformed(evt);
            }
        });
        getContentPane().add(btnAccountManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, -1, 30));

        jPanel1.setVisible(false);
        jPanel1.setLayout(new java.awt.CardLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountManagerActionPerformed
//        g = new GameFrame();
//        g.setVisible(true);
//        g.accountManager();
        this.dispose();
    }//GEN-LAST:event_btnAccountManagerActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        jPanel1.setVisible(true);
        CardLayout CL = (CardLayout)jPanel1.getLayout();
        CL.show(jPanel1, "GamePanel");
//        g = new GameFrame();
//        g.startGame();
//        g.getRootPane().requestFocus();
//        //        g.requestFocusInWindow();
//        g.setVisible(true);
//        System.out.println(g.isFocused());
//        this.dispose();
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnLevelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLevelsActionPerformed
//        g = new GameFrame();
//        g.setVisible(true);
//        g.levels();
        this.dispose();
    }//GEN-LAST:event_btnLevelsActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrickBreakerManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrickBreakerManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrickBreakerManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrickBreakerManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrickBreakerManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountManager;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLevels;
    private javax.swing.JButton btnOptions;
    private javax.swing.JButton btnPlay;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private final GamePanel gamePanel;
    private final LevelCreatorWizard levelCreator;
    private final AccountManager mainDesk;
    private final LEVELS level;
    private final javax.swing.JScrollPane pane;
    private final ScoreManager scoreScreen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblExit1;
    private javax.swing.JLabel lblExit2;
    private javax.swing.JLabel lblHelp1;
    private javax.swing.JLabel lblHelp2;
    private javax.swing.JLabel lblLevels1;
    private javax.swing.JLabel lblLevels2;
    private javax.swing.JLabel lblOptions1;
    private javax.swing.JLabel lblOptions2;
    private javax.swing.JLabel lblPlay1;
    private javax.swing.JLabel lblPlay2;
    // End of variables declaration//GEN-END:variables

//    @Override
//    public void run() {
//        long lastTime = System.nanoTime();
//        final double amountOfTicks = 60;
//        double nanoSeconds = 1000000000 / amountOfTicks;
//        double delta = 0;
//        double time = 0;
//        while (myThread.isAlive()) {
//            long now = System.nanoTime();
//            delta += (now - lastTime) / nanoSeconds;
//            lastTime = now;
//            if (delta >= 1) {
//                if (loggedIn) {
//                    btnAccountManager.setText("Logged In");
//                }
//                repaint();
//            }
//        }
//    }
    @Override
    public void paint(Graphics grphcs) {
        super.paint(grphcs);
    }

    @Override
    public void mouseClicked(MouseEvent me) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mousePressed(MouseEvent me) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent me) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent me) {
        if (me.getSource().equals(btnPlay)) {
            lblPlay1.setVisible(true);
            lblPlay2.setVisible(true);
            btnPlay.setFont(new Font(btnPlay.getFont().toString(), Font.BOLD, 18));
        }
        if (me.getSource().equals(btnLevels)) {
            lblLevels1.setVisible(true);
            lblLevels2.setVisible(true);
            btnLevels.setFont(new Font(btnLevels.getFont().toString(), Font.BOLD, 18));
        }
        if (me.getSource().equals(btnOptions)) {
            lblOptions1.setVisible(true);
            lblOptions2.setVisible(true);
            btnOptions.setFont(new Font(btnOptions.getFont().toString(), Font.BOLD, 18));
        }
        if (me.getSource().equals(btnHelp)) {
            lblHelp1.setVisible(true);
            lblHelp2.setVisible(true);
            btnHelp.setFont(new Font(btnHelp.getFont().toString(), Font.BOLD, 18));
        }
        if (me.getSource().equals(btnExit)) {
            lblExit1.setVisible(true);
            lblExit2.setVisible(true);
            btnExit.setFont(new Font(btnExit.getFont().toString(), Font.BOLD, 18));
        }
        if (me.getSource().equals(btnAccountManager) && !loggedIn) {
            btnAccountManager.setFont(new Font(btnAccountManager.getFont().toString(), Font.BOLD, 18));
        }
    }

    @Override
    public void mouseExited(MouseEvent me) {
        if (me.getSource().equals(btnPlay)) {
            lblPlay1.setVisible(false);
            lblPlay2.setVisible(false);
            btnPlay.setFont(new Font(btnPlay.getFont().toString(), Font.BOLD, 16));
        }
        if (me.getSource().equals(btnLevels)) {
            lblLevels1.setVisible(false);
            lblLevels2.setVisible(false);
            btnLevels.setFont(new Font(btnLevels.getFont().toString(), Font.BOLD, 16));
        }
        if (me.getSource().equals(btnOptions)) {
            lblOptions1.setVisible(false);
            lblOptions2.setVisible(false);
            btnOptions.setFont(new Font(btnOptions.getFont().toString(), Font.BOLD, 16));
        }
        if (me.getSource().equals(btnHelp)) {
            lblHelp1.setVisible(false);
            lblHelp2.setVisible(false);
            btnHelp.setFont(new Font(btnHelp.getFont().toString(), Font.BOLD, 16));
        }
        if (me.getSource().equals(btnExit)) {
            lblExit1.setVisible(false);
            lblExit2.setVisible(false);
            btnExit.setFont(new Font(btnExit.getFont().toString(), Font.BOLD, 16));
        }
        if (me.getSource().equals(btnAccountManager) && !loggedIn) {
            btnAccountManager.setFont(new Font(btnAccountManager.getFont().toString(), Font.BOLD, 16));
        }
    }
}
